//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentAssertions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FluentAssertions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluentAssertions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FluentAssertions.FluentAssertions", typeof(FluentAssertions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string XmlElementAssertions_HaveInnerText_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlElementAssertions_HaveInnerText_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlElementAssertions_HaveAttributeWithNamespace_AttributeIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlElementAssertions_HaveAttributeWithNamespace_AttributeIsNull_FailMessageFormat" +
                        "", resourceCulture);
            }
        }
        
        internal static string XmlElementAssertions_HaveAttributeWithNamespace_AttributeHaveIncorrectValue_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlElementAssertions_HaveAttributeWithNamespace_AttributeHaveIncorrectValue_FailM" +
                        "essageFormat", resourceCulture);
            }
        }
        
        internal static string XmlElementAssertions_HaveElementWithNamespace_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlElementAssertions_HaveElementWithNamespace_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string ObjectAssertions_BeDataContractSerializable_FailMessageFormat {
            get {
                return ResourceManager.GetString("ObjectAssertions_BeDataContractSerializable_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string ObjectAssertions_BeXmlSerializable_FailMessageFormat {
            get {
                return ResourceManager.GetString("ObjectAssertions_BeXmlSerializable_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_NotBeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_NotBeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_NotBeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_NotBeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfDouble_NotBeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfDouble_NotBeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfFloat_NotBeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfFloat_NotBeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_BeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_BeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_BeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_BeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfDouble_BeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfDouble_BeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfFloat_BeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfFloat_BeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertions_FailIfDifferenceWithinPrecision_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertions_FailIfDifferenceWithinPrecision_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDecimal_NotBeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDecimal_NotBeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_NotBeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_NotBeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_NotBeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_NotBeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfT_FailIfDifferenceOutsidePrecision_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfT_FailIfDifferenceOutsidePrecision_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDecimal_BeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDecimal_BeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_BeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_BeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_BeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_BeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDecimal_BeApproximatelyWhenValueIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDecimal_BeApproximatelyWhenValueIsNull_FailMessageForm" +
                        "at", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_BeApproximatelyWhenValueIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_BeApproximatelyWhenValueIsNull_FailMessageForma" +
                        "t", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_BeApproximatelyWhenValueIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_BeApproximatelyWhenValueIsNull_FailMessageFormat" +
                        "", resourceCulture);
            }
        }
        
        internal static string NumericAssertions_FailIfValueInsideBounds_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertions_FailIfValueInsideBounds_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertions_FailIfValueOutsideBounds_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertions_FailIfValueOutsideBounds_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string ExceptionAssertions_WithParameterName_FailMessageFormat {
            get {
                return ResourceManager.GetString("ExceptionAssertions_WithParameterName_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string OccurrenceConstraint_ExceptionMessage {
            get {
                return ResourceManager.GetString("OccurrenceConstraint_ExceptionMessage", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithSender_EveryEvent_FailMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithSender_EveryEvent_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithSender_Senders_FailMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithSender_Senders_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithArgs_FailMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithArgs_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithArgs_EventArgumentException_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithArgs_EventArgumentException_ExceptionMessageFormat", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithArgs_FoundMatchingEvent_FailMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithArgs_FoundMatchingEvent_FailMessageFormat", resourceCulture);
            }
        }
    }
}
