//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentAssertions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FluentAssertions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluentAssertions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FluentAssertions.FluentAssertions", typeof(FluentAssertions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string XmlElementAssertions_HaveInnerText_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlElementAssertions_HaveInnerText_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlElementAssertions_HaveAttributeWithNamespace_AttributeIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlElementAssertions_HaveAttributeWithNamespace_AttributeIsNull_FailMessageFormat" +
                        "", resourceCulture);
            }
        }
        
        internal static string XmlElementAssertions_HaveAttributeWithNamespace_AttributeHaveIncorrectValue_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlElementAssertions_HaveAttributeWithNamespace_AttributeHaveIncorrectValue_FailM" +
                        "essageFormat", resourceCulture);
            }
        }
        
        internal static string XmlElementAssertions_HaveElementWithNamespace_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlElementAssertions_HaveElementWithNamespace_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string ObjectAssertions_BeDataContractSerializable_FailMessageFormat {
            get {
                return ResourceManager.GetString("ObjectAssertions_BeDataContractSerializable_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string ObjectAssertions_BeXmlSerializable_FailMessageFormat {
            get {
                return ResourceManager.GetString("ObjectAssertions_BeXmlSerializable_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_NotBeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_NotBeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_NotBeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_NotBeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfDouble_NotBeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfDouble_NotBeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfFloat_NotBeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfFloat_NotBeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_BeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_BeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_BeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_BeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfDouble_BeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfDouble_BeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfFloat_BeNaN_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfFloat_BeNaN_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertions_FailIfDifferenceWithinPrecision_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertions_FailIfDifferenceWithinPrecision_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDecimal_NotBeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDecimal_NotBeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_NotBeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_NotBeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_NotBeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_NotBeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfT_FailIfDifferenceOutsidePrecision_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfT_FailIfDifferenceOutsidePrecision_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDecimal_BeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDecimal_BeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_BeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_BeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_BeApproximately_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_BeApproximately_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDecimal_BeApproximatelyWhenValueIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDecimal_BeApproximatelyWhenValueIsNull_FailMessageForm" +
                        "at", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfDouble_BeApproximatelyWhenValueIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfDouble_BeApproximatelyWhenValueIsNull_FailMessageForma" +
                        "t", resourceCulture);
            }
        }
        
        internal static string NullableNumericAssertionsOfFloat_BeApproximatelyWhenValueIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("NullableNumericAssertionsOfFloat_BeApproximatelyWhenValueIsNull_FailMessageFormat" +
                        "", resourceCulture);
            }
        }
        
        internal static string NumericAssertions_FailIfValueInsideBounds_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertions_FailIfValueInsideBounds_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertions_FailIfValueOutsideBounds_FailMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertions_FailIfValueOutsideBounds_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string ExceptionAssertions_WithParameterName_FailMessageFormat {
            get {
                return ResourceManager.GetString("ExceptionAssertions_WithParameterName_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string OccurrenceConstraint_ExceptionMessage {
            get {
                return ResourceManager.GetString("OccurrenceConstraint_ExceptionMessage", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithSender_EveryEvent_FailMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithSender_EveryEvent_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithSender_Senders_FailMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithSender_Senders_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithArgs_FailMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithArgs_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithArgs_EventArgumentException_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithArgs_EventArgumentException_ExceptionMessageFormat", resourceCulture);
            }
        }
        
        internal static string EventRaisingExtensions_WithArgs_FoundMatchingEvent_FailMessageFormat {
            get {
                return ResourceManager.GetString("EventRaisingExtensions_WithArgs_FoundMatchingEvent_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveValue_SubjectIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveValue_SubjectIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveValue_SubjectIsNotEqualExpected_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveValue_SubjectIsNotEqualExpected_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveAttribute_SubjectIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveAttribute_SubjectIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveAttribute_AttributeIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveAttribute_AttributeIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveAttribute_AttributeIsNotEqualExpected_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveAttribute_AttributeIsNotEqualExpected_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveElement_SubjectIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveElement_SubjectIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveElement_ElementIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveElement_ElementIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveElement_GuardExpectedValue_GuardMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveElement_GuardExpectedValue_GuardMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveElementForEnumerable_SubjectIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveElementForEnumerable_SubjectIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveElementForEnumerable_OccurrenceConstraint_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveElementForEnumerable_OccurrenceConstraint_FailMessageForma" +
                        "t", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_HaveElementForEnumerable_GuardExpectedValue_GuardMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_HaveElementForEnumerable_GuardExpectedValue_GuardMessageFormat" +
                        "", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_NotBe_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_NotBe_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XElementAssertions_Be_FailMessageFormat {
            get {
                return ResourceManager.GetString("XElementAssertions_Be_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfFloat_BeApproximately_ArgumentException_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfFloat_BeApproximately_ArgumentException_ExceptionMessageFormat" +
                        "", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfDouble_BeApproximately_ArgumentException_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfDouble_BeApproximately_ArgumentException_ExceptionMessageForma" +
                        "t", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfFloat_NotBeApproximately_ArgumentException_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfFloat_NotBeApproximately_ArgumentException_ExceptionMessageFor" +
                        "mat", resourceCulture);
            }
        }
        
        internal static string NumericAssertionsOfDouble_NotBeApproximately_ArgumentException_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("NumericAssertionsOfDouble_NotBeApproximately_ArgumentException_ExceptionMessageFo" +
                        "rmat", resourceCulture);
            }
        }
        
        internal static string AndWhichConstraint_SingleOrDefault_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("AndWhichConstraint_SingleOrDefault_ExceptionMessageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_Be_SubjectNotEqualsExpected_FailMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_Be_SubjectNotEqualsExpected_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_NotBe_SubjectEqualsUneExpected_FailMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_NotBe_SubjectEqualsUneExpected_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveRoot_GuardThrowIfArgumentIsNull_GuardMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveRoot_GuardThrowIfArgumentIsNull_GuardMessageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveRoot_InvalidOperationException_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveRoot_InvalidOperationException_ExceptionMessageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveRoot_GuardThrowIfArgumentIsNull_ForElement_GuardMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveRoot_GuardThrowIfArgumentIsNull_ForElement_GuardMessageFo" +
                        "rmat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveRoot_RootIsNullAndNameIsNotEqualExpected_FailMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveRoot_RootIsNullAndNameIsNotEqualExpected_FailMessageForma" +
                        "t", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElement_GuardThrowIfArgumentIsNull_StringExpected_GuardMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElement_GuardThrowIfArgumentIsNull_StringExpected_GuardMe" +
                        "ssageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElement_GuardThrowIfArgumentIsNull_OccurrenceConstraint_GuardMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElement_GuardThrowIfArgumentIsNull_OccurrenceConstraint_G" +
                        "uardMessageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElement_GuardThrowIfArgumentIsNull_XName_GuardMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElement_GuardThrowIfArgumentIsNull_XName_GuardMessageForm" +
                        "at", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElement_InvalidOperationException_XName_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElement_InvalidOperationException_XName_ExceptionMessageF" +
                        "ormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElement_SubjectRootIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElement_SubjectRootIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElement_ElementIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElement_ElementIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElementForEnumerableOfXElement_GuardThrowIfArgumentIsNull_GuardMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElementForEnumerableOfXElement_GuardThrowIfArgumentIsNull" +
                        "_GuardMessageFormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElementForEnumerableOfXElement_SubjectIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElementForEnumerableOfXElement_SubjectIsNull_FailMessageF" +
                        "ormat", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElementForEnumerableOfXElement_RootIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElementForEnumerableOfXElement_RootIsNull_FailMessageForm" +
                        "at", resourceCulture);
            }
        }
        
        internal static string XDocumentAssertions_HaveElementForEnumerableOfXElement_OccurrenceConstraint_FailMessageFormat {
            get {
                return ResourceManager.GetString("XDocumentAssertions_HaveElementForEnumerableOfXElement_OccurrenceConstraint_FailM" +
                        "essageFormat", resourceCulture);
            }
        }
        
        internal static string XAttributeAssertions_Be_SubjectNotEqualsExpected_FailMessageFormat {
            get {
                return ResourceManager.GetString("XAttributeAssertions_Be_SubjectNotEqualsExpected_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XAttributeAssertions_NotBe_SubjectEqualsUneExpected_FailMessageFormat {
            get {
                return ResourceManager.GetString("XAttributeAssertions_NotBe_SubjectEqualsUneExpected_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XAttributeAssertions_HaveValue_SubjectIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XAttributeAssertions_HaveValue_SubjectIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XAttributeAssertions_HaveValue_SubjectIsNotEqualExpected_FailMessageFormat {
            get {
                return ResourceManager.GetString("XAttributeAssertions_HaveValue_SubjectIsNotEqualExpected_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_Validate_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_Validate_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_Validate_Content_MessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_Validate_Content_MessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_Validate_SubjectNotEqualExpectation_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_Validate_SubjectNotEqualExpectation_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_Validate_NotSupportedException_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_Validate_NotSupportedException_ExceptionMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_Validate_ExpectationNotEndOfDocument_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_Validate_ExpectationNotEndOfDocument_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_Validate_SubjectNotEndOfDocument_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_Validate_SubjectNotEndOfDocument_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_ValidateAttributes_ExpectedAttributeIsNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_ValidateAttributes_ExpectedAttributeIsNull_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_ValidateAttributes_SubjectAttributeIsNotEqualToExpectedAttribute_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_ValidateAttributes_SubjectAttributeIsNotEqualToExpectedAttribu" +
                        "te_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_ValidateAttributes_SubjectAttributesCountIsNotEqualToExpectedAttributesCount_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_ValidateAttributes_SubjectAttributesCountIsNotEqualToExpectedA" +
                        "ttributesCount_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_ValidateStartElement_SubjectLocalNameIsNotEqualToExpectationLocalName_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_ValidateStartElement_SubjectLocalNameIsNotEqualToExpectationLo" +
                        "calName_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_ValidateStartElement_SubjectNamespaceUriIsNotEqualToExpectationNamespaceUri_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_ValidateStartElement_SubjectNamespaceUriIsNotEqualToExpectatio" +
                        "nNamespaceUri_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_ValidateText_SubjectIsNotEqualToExpectation_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_ValidateText_SubjectIsNotEqualToExpectation_FailMessageFormat", resourceCulture);
            }
        }
        
        internal static string XmlReaderValidator_ValidateAgainstNulls_SubjectAndExpectationIsNotNull_FailMessageFormat {
            get {
                return ResourceManager.GetString("XmlReaderValidator_ValidateAgainstNulls_SubjectAndExpectationIsNotNull_FailMessag" +
                        "eFormat", resourceCulture);
            }
        }
    }
}
